# Generated by Django 2.0.6 on 2018-06-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180625_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('femail', 'Female'), ('not-specified', 'Not Specified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
