# Generated by Django 2.0.6 on 2018-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180809_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('male', 'Male'), ('femail', 'Female')], max_length=80, null=True),
        ),
    ]
