# Generated by Django 2.0.6 on 2018-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180811_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('femail', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
